// Copyright 2017-2021 @bholdus/api-options authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@bholdus/api-options', version: '0.3.0' };
